package br.b4hive;

/**
 *
 * @author Bruno dos Santos
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapOuterJPanel = new javax.swing.JPanel();
        mapJSplitPane = new javax.swing.JSplitPane();
        mapGridJPanel = new javax.swing.JPanel();
        tile_n3w3 = new javax.swing.JPanel();
        bot_n3w3 = new javax.swing.JLabel();
        tile_n3w2 = new javax.swing.JPanel();
        bot_n3w2 = new javax.swing.JLabel();
        tile_n3w1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tile_n3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tile_n3e1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tile_n3e2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        tile_n3e3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        tile_n2w3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        tile_n2w2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        tile_n2w1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        tile_n2 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        tile_n2e1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        tile_n2e2 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        tile_n2e3 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        tile_n1w3 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        tile_n1w2 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        tile_n1w1 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        tile_n1 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        tile_n1e1 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        tile_n1e2 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        tile_n1e3 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        tile_w3 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        tile_w2 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        tile_w1 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        tile_0 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        tile_e1 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        tile_e2 = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        tile_e3 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        tile_s1w3 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        tile_s1w2 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        tile_s1w1 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        tile_s1 = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        tile_s1e1 = new javax.swing.JPanel();
        jLabel96 = new javax.swing.JLabel();
        tile_s1e2 = new javax.swing.JPanel();
        jLabel99 = new javax.swing.JLabel();
        tile_s1e3 = new javax.swing.JPanel();
        jLabel102 = new javax.swing.JLabel();
        tile_s2w3 = new javax.swing.JPanel();
        jLabel105 = new javax.swing.JLabel();
        tile_s2w2 = new javax.swing.JPanel();
        jLabel108 = new javax.swing.JLabel();
        tile_s2w1 = new javax.swing.JPanel();
        jLabel111 = new javax.swing.JLabel();
        tile_s2 = new javax.swing.JPanel();
        jLabel114 = new javax.swing.JLabel();
        tile_s2e1 = new javax.swing.JPanel();
        jLabel117 = new javax.swing.JLabel();
        tile_s2e2 = new javax.swing.JPanel();
        jLabel120 = new javax.swing.JLabel();
        tile_s2e3 = new javax.swing.JPanel();
        jLabel123 = new javax.swing.JLabel();
        tile_s3w3 = new javax.swing.JPanel();
        jLabel129 = new javax.swing.JLabel();
        tile_s3w2 = new javax.swing.JPanel();
        jLabel132 = new javax.swing.JLabel();
        tile_s3w1 = new javax.swing.JPanel();
        jLabel135 = new javax.swing.JLabel();
        tile_s3 = new javax.swing.JPanel();
        jLabel138 = new javax.swing.JLabel();
        tile_s3e1 = new javax.swing.JPanel();
        jLabel141 = new javax.swing.JLabel();
        tile_s3e2 = new javax.swing.JPanel();
        jLabel144 = new javax.swing.JLabel();
        tile_s3e3 = new javax.swing.JPanel();
        jLabel147 = new javax.swing.JLabel();
        sideJPanel = new javax.swing.JPanel();
        healthBarJLabel = new javax.swing.JLabel();
        HealthJProgressBar = new javax.swing.JProgressBar();
        energyBarJLabel = new javax.swing.JLabel();
        EnergyJProgressBar = new javax.swing.JProgressBar();
        miniMapJPanel = new javax.swing.JPanel();
        titleJPanel = new javax.swing.JPanel();
        titleJLabel = new javax.swing.JLabel();
        mainJMenuBar = new javax.swing.JMenuBar();
        GameJMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lone Beehive: Megachile");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        mapOuterJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mapOuterJPanel.setLayout(new java.awt.BorderLayout());

        mapJSplitPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mapJSplitPane.setDividerLocation(560);
        mapJSplitPane.setDividerSize(0);

        mapGridJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mapGridJPanel.setMaximumSize(new java.awt.Dimension(560, 560));
        mapGridJPanel.setMinimumSize(new java.awt.Dimension(560, 560));
        mapGridJPanel.setPreferredSize(new java.awt.Dimension(560, 560));
        mapGridJPanel.setLayout(new java.awt.GridLayout(7, 7));

        tile_n3w3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n3w3.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n3w3.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n3w3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n3w3.setLayout(new javax.swing.OverlayLayout(tile_n3w3));

        bot_n3w3.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        bot_n3w3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bot_n3w3.setText("#");
        bot_n3w3.setMaximumSize(new java.awt.Dimension(80, 80));
        bot_n3w3.setMinimumSize(new java.awt.Dimension(80, 80));
        bot_n3w3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n3w3.add(bot_n3w3);

        mapGridJPanel.add(tile_n3w3);

        tile_n3w2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n3w2.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n3w2.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n3w2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n3w2.setLayout(new javax.swing.OverlayLayout(tile_n3w2));

        bot_n3w2.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        bot_n3w2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bot_n3w2.setText("#");
        bot_n3w2.setMaximumSize(new java.awt.Dimension(80, 80));
        bot_n3w2.setMinimumSize(new java.awt.Dimension(80, 80));
        bot_n3w2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n3w2.add(bot_n3w2);

        mapGridJPanel.add(tile_n3w2);

        tile_n3w1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n3w1.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n3w1.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n3w1.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n3w1.setLayout(new javax.swing.OverlayLayout(tile_n3w1));

        jLabel6.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("#");
        jLabel6.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel6.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel6.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n3w1.add(jLabel6);

        mapGridJPanel.add(tile_n3w1);

        tile_n3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n3.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n3.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n3.setLayout(new javax.swing.OverlayLayout(tile_n3));

        jLabel9.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("#");
        jLabel9.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel9.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel9.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n3.add(jLabel9);

        mapGridJPanel.add(tile_n3);

        tile_n3e1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n3e1.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n3e1.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n3e1.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n3e1.setLayout(new javax.swing.OverlayLayout(tile_n3e1));

        jLabel12.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("#");
        jLabel12.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel12.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel12.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n3e1.add(jLabel12);

        mapGridJPanel.add(tile_n3e1);

        tile_n3e2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n3e2.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n3e2.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n3e2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n3e2.setLayout(new javax.swing.OverlayLayout(tile_n3e2));

        jLabel15.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("#");
        jLabel15.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel15.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel15.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n3e2.add(jLabel15);

        mapGridJPanel.add(tile_n3e2);

        tile_n3e3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n3e3.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n3e3.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n3e3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n3e3.setLayout(new javax.swing.OverlayLayout(tile_n3e3));

        jLabel18.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("#");
        jLabel18.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel18.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel18.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n3e3.add(jLabel18);

        mapGridJPanel.add(tile_n3e3);

        tile_n2w3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n2w3.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n2w3.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n2w3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n2w3.setLayout(new javax.swing.OverlayLayout(tile_n2w3));

        jLabel21.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("#");
        jLabel21.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel21.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel21.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n2w3.add(jLabel21);

        mapGridJPanel.add(tile_n2w3);

        tile_n2w2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n2w2.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n2w2.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n2w2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n2w2.setLayout(new javax.swing.OverlayLayout(tile_n2w2));

        jLabel24.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("#");
        jLabel24.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel24.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel24.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n2w2.add(jLabel24);

        mapGridJPanel.add(tile_n2w2);

        tile_n2w1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n2w1.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n2w1.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n2w1.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n2w1.setLayout(new javax.swing.OverlayLayout(tile_n2w1));

        jLabel27.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("#");
        jLabel27.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel27.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel27.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n2w1.add(jLabel27);

        mapGridJPanel.add(tile_n2w1);

        tile_n2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n2.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n2.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n2.setLayout(new javax.swing.OverlayLayout(tile_n2));

        jLabel30.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("#");
        jLabel30.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel30.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel30.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n2.add(jLabel30);

        mapGridJPanel.add(tile_n2);

        tile_n2e1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n2e1.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n2e1.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n2e1.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n2e1.setLayout(new javax.swing.OverlayLayout(tile_n2e1));

        jLabel33.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("#");
        jLabel33.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel33.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel33.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n2e1.add(jLabel33);

        mapGridJPanel.add(tile_n2e1);

        tile_n2e2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n2e2.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n2e2.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n2e2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n2e2.setLayout(new javax.swing.OverlayLayout(tile_n2e2));

        jLabel36.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("#");
        jLabel36.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel36.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel36.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n2e2.add(jLabel36);

        mapGridJPanel.add(tile_n2e2);

        tile_n2e3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n2e3.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n2e3.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n2e3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n2e3.setLayout(new javax.swing.OverlayLayout(tile_n2e3));

        jLabel39.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("#");
        jLabel39.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel39.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel39.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n2e3.add(jLabel39);

        mapGridJPanel.add(tile_n2e3);

        tile_n1w3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n1w3.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n1w3.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n1w3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n1w3.setLayout(new javax.swing.OverlayLayout(tile_n1w3));

        jLabel42.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("#");
        jLabel42.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel42.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel42.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n1w3.add(jLabel42);

        mapGridJPanel.add(tile_n1w3);

        tile_n1w2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n1w2.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n1w2.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n1w2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n1w2.setLayout(new javax.swing.OverlayLayout(tile_n1w2));

        jLabel45.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("#");
        jLabel45.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel45.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel45.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n1w2.add(jLabel45);

        mapGridJPanel.add(tile_n1w2);

        tile_n1w1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n1w1.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n1w1.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n1w1.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n1w1.setLayout(new javax.swing.OverlayLayout(tile_n1w1));

        jLabel48.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("#");
        jLabel48.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel48.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel48.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n1w1.add(jLabel48);

        mapGridJPanel.add(tile_n1w1);

        tile_n1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n1.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n1.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n1.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n1.setLayout(new javax.swing.OverlayLayout(tile_n1));

        jLabel51.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("#");
        jLabel51.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel51.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel51.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n1.add(jLabel51);

        mapGridJPanel.add(tile_n1);

        tile_n1e1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n1e1.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n1e1.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n1e1.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n1e1.setLayout(new javax.swing.OverlayLayout(tile_n1e1));

        jLabel54.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("#");
        jLabel54.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel54.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel54.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n1e1.add(jLabel54);

        mapGridJPanel.add(tile_n1e1);

        tile_n1e2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n1e2.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n1e2.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n1e2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n1e2.setLayout(new javax.swing.OverlayLayout(tile_n1e2));

        jLabel57.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("#");
        jLabel57.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel57.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel57.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n1e2.add(jLabel57);

        mapGridJPanel.add(tile_n1e2);

        tile_n1e3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_n1e3.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_n1e3.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_n1e3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n1e3.setLayout(new javax.swing.OverlayLayout(tile_n1e3));

        jLabel60.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("#");
        jLabel60.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel60.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel60.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_n1e3.add(jLabel60);

        mapGridJPanel.add(tile_n1e3);

        tile_w3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_w3.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_w3.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_w3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_w3.setLayout(new javax.swing.OverlayLayout(tile_w3));

        jLabel63.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("#");
        jLabel63.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel63.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel63.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_w3.add(jLabel63);

        mapGridJPanel.add(tile_w3);

        tile_w2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_w2.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_w2.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_w2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_w2.setLayout(new javax.swing.OverlayLayout(tile_w2));

        jLabel66.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("#");
        jLabel66.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel66.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel66.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_w2.add(jLabel66);

        mapGridJPanel.add(tile_w2);

        tile_w1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_w1.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_w1.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_w1.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_w1.setLayout(new javax.swing.OverlayLayout(tile_w1));

        jLabel69.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("#");
        jLabel69.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel69.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel69.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_w1.add(jLabel69);

        mapGridJPanel.add(tile_w1);

        tile_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_0.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_0.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_0.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_0.setLayout(new javax.swing.OverlayLayout(tile_0));

        jLabel72.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("#");
        jLabel72.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel72.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel72.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_0.add(jLabel72);

        mapGridJPanel.add(tile_0);

        tile_e1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_e1.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_e1.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_e1.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_e1.setLayout(new javax.swing.OverlayLayout(tile_e1));

        jLabel75.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setText("#");
        jLabel75.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel75.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel75.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_e1.add(jLabel75);

        mapGridJPanel.add(tile_e1);

        tile_e2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_e2.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_e2.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_e2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_e2.setLayout(new javax.swing.OverlayLayout(tile_e2));

        jLabel78.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel78.setText("#");
        jLabel78.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel78.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel78.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_e2.add(jLabel78);

        mapGridJPanel.add(tile_e2);

        tile_e3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_e3.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_e3.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_e3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_e3.setLayout(new javax.swing.OverlayLayout(tile_e3));

        jLabel81.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel81.setText("#");
        jLabel81.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel81.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel81.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_e3.add(jLabel81);

        mapGridJPanel.add(tile_e3);

        tile_s1w3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s1w3.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s1w3.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s1w3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s1w3.setLayout(new javax.swing.OverlayLayout(tile_s1w3));

        jLabel84.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel84.setText("#");
        jLabel84.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel84.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel84.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s1w3.add(jLabel84);

        mapGridJPanel.add(tile_s1w3);

        tile_s1w2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s1w2.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s1w2.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s1w2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s1w2.setLayout(new javax.swing.OverlayLayout(tile_s1w2));

        jLabel87.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel87.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel87.setText("#");
        jLabel87.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel87.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel87.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s1w2.add(jLabel87);

        mapGridJPanel.add(tile_s1w2);

        tile_s1w1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s1w1.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s1w1.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s1w1.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s1w1.setLayout(new javax.swing.OverlayLayout(tile_s1w1));

        jLabel90.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel90.setText("#");
        jLabel90.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel90.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel90.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s1w1.add(jLabel90);

        mapGridJPanel.add(tile_s1w1);

        tile_s1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s1.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s1.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s1.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s1.setLayout(new javax.swing.OverlayLayout(tile_s1));

        jLabel93.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel93.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel93.setText("#");
        jLabel93.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel93.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel93.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s1.add(jLabel93);

        mapGridJPanel.add(tile_s1);

        tile_s1e1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s1e1.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s1e1.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s1e1.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s1e1.setLayout(new javax.swing.OverlayLayout(tile_s1e1));

        jLabel96.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel96.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel96.setText("#");
        jLabel96.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel96.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel96.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s1e1.add(jLabel96);

        mapGridJPanel.add(tile_s1e1);

        tile_s1e2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s1e2.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s1e2.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s1e2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s1e2.setLayout(new javax.swing.OverlayLayout(tile_s1e2));

        jLabel99.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel99.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel99.setText("#");
        jLabel99.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel99.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel99.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s1e2.add(jLabel99);

        mapGridJPanel.add(tile_s1e2);

        tile_s1e3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s1e3.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s1e3.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s1e3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s1e3.setLayout(new javax.swing.OverlayLayout(tile_s1e3));

        jLabel102.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel102.setText("#");
        jLabel102.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel102.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel102.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s1e3.add(jLabel102);

        mapGridJPanel.add(tile_s1e3);

        tile_s2w3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s2w3.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s2w3.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s2w3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s2w3.setLayout(new javax.swing.OverlayLayout(tile_s2w3));

        jLabel105.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel105.setText("#");
        jLabel105.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel105.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel105.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s2w3.add(jLabel105);

        mapGridJPanel.add(tile_s2w3);

        tile_s2w2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s2w2.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s2w2.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s2w2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s2w2.setLayout(new javax.swing.OverlayLayout(tile_s2w2));

        jLabel108.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel108.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel108.setText("#");
        jLabel108.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel108.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel108.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s2w2.add(jLabel108);

        mapGridJPanel.add(tile_s2w2);

        tile_s2w1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s2w1.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s2w1.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s2w1.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s2w1.setLayout(new javax.swing.OverlayLayout(tile_s2w1));

        jLabel111.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel111.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel111.setText("#");
        jLabel111.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel111.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel111.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s2w1.add(jLabel111);

        mapGridJPanel.add(tile_s2w1);

        tile_s2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s2.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s2.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s2.setLayout(new javax.swing.OverlayLayout(tile_s2));

        jLabel114.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel114.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel114.setText("#");
        jLabel114.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel114.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel114.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s2.add(jLabel114);

        mapGridJPanel.add(tile_s2);

        tile_s2e1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s2e1.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s2e1.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s2e1.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s2e1.setLayout(new javax.swing.OverlayLayout(tile_s2e1));

        jLabel117.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel117.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel117.setText("#");
        jLabel117.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel117.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel117.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s2e1.add(jLabel117);

        mapGridJPanel.add(tile_s2e1);

        tile_s2e2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s2e2.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s2e2.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s2e2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s2e2.setLayout(new javax.swing.OverlayLayout(tile_s2e2));

        jLabel120.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel120.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel120.setText("#");
        jLabel120.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel120.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel120.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s2e2.add(jLabel120);

        mapGridJPanel.add(tile_s2e2);

        tile_s2e3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s2e3.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s2e3.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s2e3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s2e3.setLayout(new javax.swing.OverlayLayout(tile_s2e3));

        jLabel123.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel123.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel123.setText("#");
        jLabel123.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel123.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel123.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s2e3.add(jLabel123);

        mapGridJPanel.add(tile_s2e3);

        tile_s3w3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s3w3.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s3w3.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s3w3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s3w3.setLayout(new javax.swing.OverlayLayout(tile_s3w3));

        jLabel129.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel129.setText("#");
        jLabel129.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel129.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel129.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s3w3.add(jLabel129);

        mapGridJPanel.add(tile_s3w3);

        tile_s3w2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s3w2.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s3w2.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s3w2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s3w2.setLayout(new javax.swing.OverlayLayout(tile_s3w2));

        jLabel132.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel132.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel132.setText("#");
        jLabel132.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel132.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel132.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s3w2.add(jLabel132);

        mapGridJPanel.add(tile_s3w2);

        tile_s3w1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s3w1.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s3w1.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s3w1.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s3w1.setLayout(new javax.swing.OverlayLayout(tile_s3w1));

        jLabel135.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel135.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel135.setText("#");
        jLabel135.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel135.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel135.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s3w1.add(jLabel135);

        mapGridJPanel.add(tile_s3w1);

        tile_s3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s3.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s3.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s3.setLayout(new javax.swing.OverlayLayout(tile_s3));

        jLabel138.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel138.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel138.setText("#");
        jLabel138.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel138.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel138.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s3.add(jLabel138);

        mapGridJPanel.add(tile_s3);

        tile_s3e1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s3e1.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s3e1.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s3e1.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s3e1.setLayout(new javax.swing.OverlayLayout(tile_s3e1));

        jLabel141.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel141.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel141.setText("#");
        jLabel141.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel141.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel141.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s3e1.add(jLabel141);

        mapGridJPanel.add(tile_s3e1);

        tile_s3e2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s3e2.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s3e2.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s3e2.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s3e2.setLayout(new javax.swing.OverlayLayout(tile_s3e2));

        jLabel144.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel144.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel144.setText("#");
        jLabel144.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel144.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel144.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s3e2.add(jLabel144);

        mapGridJPanel.add(tile_s3e2);

        tile_s3e3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tile_s3e3.setMaximumSize(new java.awt.Dimension(80, 80));
        tile_s3e3.setMinimumSize(new java.awt.Dimension(80, 80));
        tile_s3e3.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s3e3.setLayout(new javax.swing.OverlayLayout(tile_s3e3));

        jLabel147.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel147.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel147.setText("#");
        jLabel147.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel147.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel147.setPreferredSize(new java.awt.Dimension(80, 80));
        tile_s3e3.add(jLabel147);

        mapGridJPanel.add(tile_s3e3);

        mapJSplitPane.setLeftComponent(mapGridJPanel);

        sideJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sideJPanel.setMaximumSize(new java.awt.Dimension(2147483647, 240));
        sideJPanel.setMinimumSize(new java.awt.Dimension(2147483647, 240));
        sideJPanel.setPreferredSize(new java.awt.Dimension(2147483647, 240));
        sideJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        healthBarJLabel.setText("Health Points");
        healthBarJLabel.setMaximumSize(new java.awt.Dimension(230, 35));
        healthBarJLabel.setMinimumSize(new java.awt.Dimension(230, 35));
        healthBarJLabel.setPreferredSize(new java.awt.Dimension(230, 30));
        sideJPanel.add(healthBarJLabel);

        HealthJProgressBar.setForeground(new java.awt.Color(255, 0, 0));
        HealthJProgressBar.setValue(80);
        HealthJProgressBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        HealthJProgressBar.setMaximumSize(new java.awt.Dimension(230, 35));
        HealthJProgressBar.setMinimumSize(new java.awt.Dimension(230, 35));
        HealthJProgressBar.setPreferredSize(new java.awt.Dimension(230, 30));
        sideJPanel.add(HealthJProgressBar);

        energyBarJLabel.setText("Energy Points");
        energyBarJLabel.setMaximumSize(new java.awt.Dimension(230, 35));
        energyBarJLabel.setMinimumSize(new java.awt.Dimension(230, 35));
        energyBarJLabel.setPreferredSize(new java.awt.Dimension(230, 30));
        sideJPanel.add(energyBarJLabel);

        EnergyJProgressBar.setForeground(new java.awt.Color(0, 255, 0));
        EnergyJProgressBar.setValue(60);
        EnergyJProgressBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EnergyJProgressBar.setMaximumSize(new java.awt.Dimension(230, 35));
        EnergyJProgressBar.setMinimumSize(new java.awt.Dimension(230, 35));
        EnergyJProgressBar.setPreferredSize(new java.awt.Dimension(230, 30));
        sideJPanel.add(EnergyJProgressBar);

        miniMapJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        miniMapJPanel.setMaximumSize(new java.awt.Dimension(230, 230));
        miniMapJPanel.setMinimumSize(new java.awt.Dimension(230, 230));
        miniMapJPanel.setPreferredSize(new java.awt.Dimension(220, 220));
        sideJPanel.add(miniMapJPanel);

        mapJSplitPane.setRightComponent(sideJPanel);

        mapOuterJPanel.add(mapJSplitPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(mapOuterJPanel);

        titleJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        titleJPanel.setLayout(new java.awt.GridLayout(1, 0));

        titleJLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleJLabel.setText("Lone Beehive: Megachile");
        titleJPanel.add(titleJLabel);

        getContentPane().add(titleJPanel);

        GameJMenu.setText("Game");
        mainJMenuBar.add(GameJMenu);

        setJMenuBar(mainJMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar EnergyJProgressBar;
    private javax.swing.JMenu GameJMenu;
    private javax.swing.JProgressBar HealthJProgressBar;
    private javax.swing.JLabel bot_n3w2;
    private javax.swing.JLabel bot_n3w3;
    private javax.swing.JLabel energyBarJLabel;
    private javax.swing.JLabel healthBarJLabel;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JMenuBar mainJMenuBar;
    private javax.swing.JPanel mapGridJPanel;
    private javax.swing.JSplitPane mapJSplitPane;
    private javax.swing.JPanel mapOuterJPanel;
    private javax.swing.JPanel miniMapJPanel;
    private javax.swing.JPanel sideJPanel;
    private javax.swing.JPanel tile_0;
    private javax.swing.JPanel tile_e1;
    private javax.swing.JPanel tile_e2;
    private javax.swing.JPanel tile_e3;
    private javax.swing.JPanel tile_n1;
    private javax.swing.JPanel tile_n1e1;
    private javax.swing.JPanel tile_n1e2;
    private javax.swing.JPanel tile_n1e3;
    private javax.swing.JPanel tile_n1w1;
    private javax.swing.JPanel tile_n1w2;
    private javax.swing.JPanel tile_n1w3;
    private javax.swing.JPanel tile_n2;
    private javax.swing.JPanel tile_n2e1;
    private javax.swing.JPanel tile_n2e2;
    private javax.swing.JPanel tile_n2e3;
    private javax.swing.JPanel tile_n2w1;
    private javax.swing.JPanel tile_n2w2;
    private javax.swing.JPanel tile_n2w3;
    private javax.swing.JPanel tile_n3;
    private javax.swing.JPanel tile_n3e1;
    private javax.swing.JPanel tile_n3e2;
    private javax.swing.JPanel tile_n3e3;
    private javax.swing.JPanel tile_n3w1;
    private javax.swing.JPanel tile_n3w2;
    private javax.swing.JPanel tile_n3w3;
    private javax.swing.JPanel tile_s1;
    private javax.swing.JPanel tile_s1e1;
    private javax.swing.JPanel tile_s1e2;
    private javax.swing.JPanel tile_s1e3;
    private javax.swing.JPanel tile_s1w1;
    private javax.swing.JPanel tile_s1w2;
    private javax.swing.JPanel tile_s1w3;
    private javax.swing.JPanel tile_s2;
    private javax.swing.JPanel tile_s2e1;
    private javax.swing.JPanel tile_s2e2;
    private javax.swing.JPanel tile_s2e3;
    private javax.swing.JPanel tile_s2w1;
    private javax.swing.JPanel tile_s2w2;
    private javax.swing.JPanel tile_s2w3;
    private javax.swing.JPanel tile_s3;
    private javax.swing.JPanel tile_s3e1;
    private javax.swing.JPanel tile_s3e2;
    private javax.swing.JPanel tile_s3e3;
    private javax.swing.JPanel tile_s3w1;
    private javax.swing.JPanel tile_s3w2;
    private javax.swing.JPanel tile_s3w3;
    private javax.swing.JPanel tile_w1;
    private javax.swing.JPanel tile_w2;
    private javax.swing.JPanel tile_w3;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JPanel titleJPanel;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}
