package br.b4hive;

/**
 *
 * @author Bruno dos Santos
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapJPanel = new javax.swing.JPanel();
        mapGridJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        titleJPanel = new javax.swing.JPanel();
        titleJLabel = new javax.swing.JLabel();
        mainJMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lone Beehive: Megachile");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        mapJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "MapPanel"));
        mapJPanel.setLayout(new java.awt.BorderLayout());

        mapGridJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mapGridJPanel.setLayout(new java.awt.GridLayout(7, 7));

        jLabel1.setText("jLabel1");
        mapGridJPanel.add(jLabel1);

        jLabel2.setText("jLabel2");
        mapGridJPanel.add(jLabel2);

        jLabel3.setText("jLabel3");
        mapGridJPanel.add(jLabel3);

        jLabel4.setText("jLabel4");
        mapGridJPanel.add(jLabel4);

        jLabel5.setText("jLabel5");
        mapGridJPanel.add(jLabel5);

        jLabel6.setText("jLabel6");
        mapGridJPanel.add(jLabel6);

        jLabel7.setText("jLabel7");
        mapGridJPanel.add(jLabel7);

        jLabel8.setText("jLabel8");
        mapGridJPanel.add(jLabel8);

        jLabel9.setText("jLabel9");
        mapGridJPanel.add(jLabel9);

        jLabel10.setText("jLabel10");
        mapGridJPanel.add(jLabel10);

        jLabel11.setText("jLabel11");
        mapGridJPanel.add(jLabel11);

        jLabel12.setText("jLabel12");
        mapGridJPanel.add(jLabel12);

        jLabel13.setText("jLabel13");
        mapGridJPanel.add(jLabel13);

        jLabel14.setText("jLabel14");
        mapGridJPanel.add(jLabel14);

        jLabel15.setText("jLabel15");
        mapGridJPanel.add(jLabel15);

        jLabel16.setText("jLabel16");
        mapGridJPanel.add(jLabel16);

        jLabel17.setText("jLabel17");
        mapGridJPanel.add(jLabel17);

        jLabel18.setText("jLabel18");
        mapGridJPanel.add(jLabel18);

        jLabel19.setText("jLabel19");
        mapGridJPanel.add(jLabel19);

        jLabel20.setText("jLabel20");
        mapGridJPanel.add(jLabel20);

        jLabel21.setText("jLabel21");
        mapGridJPanel.add(jLabel21);

        jLabel22.setText("jLabel22");
        mapGridJPanel.add(jLabel22);

        jLabel23.setText("jLabel23");
        mapGridJPanel.add(jLabel23);

        jLabel24.setText("jLabel24");
        mapGridJPanel.add(jLabel24);

        jLabel25.setText("jLabel25");
        mapGridJPanel.add(jLabel25);

        jLabel26.setText("jLabel26");
        mapGridJPanel.add(jLabel26);

        jLabel27.setText("jLabel27");
        mapGridJPanel.add(jLabel27);

        jLabel28.setText("jLabel28");
        mapGridJPanel.add(jLabel28);

        jLabel29.setText("jLabel29");
        mapGridJPanel.add(jLabel29);

        jLabel30.setText("jLabel30");
        mapGridJPanel.add(jLabel30);

        jLabel31.setText("jLabel31");
        mapGridJPanel.add(jLabel31);

        jLabel32.setText("jLabel32");
        mapGridJPanel.add(jLabel32);

        jLabel33.setText("jLabel33");
        mapGridJPanel.add(jLabel33);

        jLabel34.setText("jLabel34");
        mapGridJPanel.add(jLabel34);

        jLabel35.setText("jLabel35");
        mapGridJPanel.add(jLabel35);

        jLabel36.setText("jLabel36");
        mapGridJPanel.add(jLabel36);

        jLabel37.setText("jLabel37");
        mapGridJPanel.add(jLabel37);

        jLabel38.setText("jLabel38");
        mapGridJPanel.add(jLabel38);

        jLabel39.setText("jLabel39");
        mapGridJPanel.add(jLabel39);

        jLabel40.setText("jLabel40");
        mapGridJPanel.add(jLabel40);

        jLabel41.setText("jLabel41");
        mapGridJPanel.add(jLabel41);

        jLabel42.setText("jLabel42");
        mapGridJPanel.add(jLabel42);

        jLabel43.setText("jLabel43");
        mapGridJPanel.add(jLabel43);

        jLabel44.setText("jLabel44");
        mapGridJPanel.add(jLabel44);

        jLabel45.setText("jLabel45");
        mapGridJPanel.add(jLabel45);

        jLabel46.setText("jLabel46");
        mapGridJPanel.add(jLabel46);

        jLabel47.setText("jLabel47");
        mapGridJPanel.add(jLabel47);

        jLabel48.setText("jLabel48");
        mapGridJPanel.add(jLabel48);

        jLabel49.setText("jLabel49");
        mapGridJPanel.add(jLabel49);

        mapJPanel.add(mapGridJPanel, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        mapJPanel.add(jPanel2, java.awt.BorderLayout.LINE_END);

        getContentPane().add(mapJPanel);

        titleJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "TitlePanel")));
        titleJPanel.setLayout(new java.awt.GridLayout());

        titleJLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleJLabel.setText("Lone Beehive: Megachile");
        titleJPanel.add(titleJLabel);

        getContentPane().add(titleJPanel);

        jMenu1.setText("File");
        mainJMenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        mainJMenuBar.add(jMenu2);

        setJMenuBar(mainJMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuBar mainJMenuBar;
    private javax.swing.JPanel mapGridJPanel;
    private javax.swing.JPanel mapJPanel;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JPanel titleJPanel;
    // End of variables declaration//GEN-END:variables
}
